#!/bin/bash 
# DOM_HOME is the variable that tells the script where the Domino Data resides 
DOM_HOME=/local/notesdata
# DOM_USER is the Linux account used to run the Domino 6 server 
DOM_USER=vagrant
# DOM_PROG is the location of the Domino executables 
DOM_PROG=/opt/ibm/domino/bin 
start() { 
    echo -n Starting domino: 
    if [ -f $DOM_HOME/.jsc_lock ]; then 
        rm $DOM_HOME/.jsc_lock 
    fi 
    cd $DOM_HOME
    sudo -u $DOM_USER $DOM_PROG/server -jc -c &
    return 0 
} 

stop() { 
    echo -n Stopping domino: 
    cd $DOM_HOME
    sudo -u $DOM_USER $DOM_PROG/server -q 
    return 0 
} 

case $1 in 
   start) 
      start 
   ;; 
   stop) 
      stop 
   ;; 
   *) 
      echo "Usage: domino {start|stop}" 
      exit 1 
esac
